[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
parking_lot = "0.12.3"
syscalls = "0.6.18"
tokio = { version = "1.43.0", features = ["rt", "io-util", "time", "sync", "fs", "macros"] }
crc64 = "2.0.0"
indexmap = "2.3.0"
log = { version = "0.4.22", features = ["kv", "kv_std"] }
rand = "0.8.5"
env_logger = { version = "0.11.3", features = ["unstable-kv"] }

[dev-dependencies]
tempfile = "3.10.1"
